"""make conversation_id nullable in checkpoints

Revision ID: 11ccaae4fb03
Revises: 27334820374b
Create Date: 2025-09-11 09:20:19.298153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '11ccaae4fb03'
down_revision: Union[str, None] = '27334820374b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only make conversation_id nullable - the main goal of this migration
    op.alter_column('conversation_checkpoints', 'conversation_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert conversation_id back to non-nullable
    op.alter_column('conversation_checkpoints', 'conversation_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
