"""remove thread_id from messages table

Revision ID: 640475800f6f
Revises: ead18872c32d
Create Date: 2025-09-18 13:29:40.320203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '640475800f6f'
down_revision: Union[str, None] = 'ead18872c32d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 跳过索引相关的操作，因为有外键约束
    # op.drop_index('idx_digital_human', table_name='digital_human_training_messages')
    # op.create_index(op.f('ix_digital_human_training_messages_digital_human_id'), 'digital_human_training_messages', ['digital_human_id'], unique=False)
    # op.create_index(op.f('ix_digital_human_training_messages_id'), 'digital_human_training_messages', ['id'], unique=False)
    # op.drop_column('digital_human_training_messages', 'session_id')
    op.alter_column('digital_humans', 'name',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='数字人名称',
               existing_nullable=False)
    op.alter_column('digital_humans', 'short_description',
               existing_type=mysql.VARCHAR(length=200),
               comment=None,
               existing_comment='简短描述',
               existing_nullable=True)
    op.alter_column('digital_humans', 'detailed_description',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='详细介绍',
               existing_nullable=True)
    op.alter_column('digital_humans', 'avatar_url',
               existing_type=mysql.VARCHAR(length=500),
               comment=None,
               existing_comment='头像URL',
               existing_nullable=True)
    op.alter_column('digital_humans', 'type',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='数字人类型',
               existing_nullable=False)
    op.alter_column('digital_humans', 'skills',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='专业领域技能列表',
               existing_nullable=True)
    op.alter_column('digital_humans', 'personality',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='性格特征配置',
               existing_nullable=True)
    op.alter_column('digital_humans', 'conversation_style',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='对话风格',
               existing_nullable=True)
    op.alter_column('digital_humans', 'temperature',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='AI温度参数',
               existing_nullable=True)
    op.alter_column('digital_humans', 'max_tokens',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='最大token数',
               existing_nullable=True)
    op.alter_column('digital_humans', 'system_prompt',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='系统提示词',
               existing_nullable=True)
    op.alter_column('digital_humans', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='模板是否启用（启用后可用于创建对话）',
               existing_nullable=True)
    op.alter_column('digital_humans', 'is_public',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否公开模板',
               existing_nullable=True)
    op.alter_column('messages', 'digital_human_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('messages', 'role',
               existing_type=mysql.ENUM('user', 'assistant', 'system'),
               comment=None,
               existing_comment='消息角色',
               existing_nullable=False)
    op.alter_column('messages', 'content',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='消息内容',
               existing_nullable=False)
    op.alter_column('messages', 'tokens_used',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='使用的token数量',
               existing_nullable=True)
    op.alter_column('messages', 'message_metadata',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='消息元数据',
               existing_nullable=True)
    op.drop_index('ix_messages_thread_id', table_name='messages')
    op.create_index(op.f('ix_messages_digital_human_id'), 'messages', ['digital_human_id'], unique=False)
    op.drop_column('messages', 'thread_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('thread_id', mysql.VARCHAR(length=100), nullable=False))
    op.drop_index(op.f('ix_messages_digital_human_id'), table_name='messages')
    op.create_index('ix_messages_thread_id', 'messages', ['thread_id'], unique=False)
    op.alter_column('messages', 'message_metadata',
               existing_type=mysql.JSON(),
               comment='消息元数据',
               existing_nullable=True)
    op.alter_column('messages', 'tokens_used',
               existing_type=mysql.INTEGER(),
               comment='使用的token数量',
               existing_nullable=True)
    op.alter_column('messages', 'content',
               existing_type=mysql.TEXT(),
               comment='消息内容',
               existing_nullable=False)
    op.alter_column('messages', 'role',
               existing_type=mysql.ENUM('user', 'assistant', 'system'),
               comment='消息角色',
               existing_nullable=False)
    op.alter_column('messages', 'digital_human_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('digital_humans', 'is_public',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否公开模板',
               existing_nullable=True)
    op.alter_column('digital_humans', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment='模板是否启用（启用后可用于创建对话）',
               existing_nullable=True)
    op.alter_column('digital_humans', 'system_prompt',
               existing_type=mysql.TEXT(),
               comment='系统提示词',
               existing_nullable=True)
    op.alter_column('digital_humans', 'max_tokens',
               existing_type=mysql.INTEGER(),
               comment='最大token数',
               existing_nullable=True)
    op.alter_column('digital_humans', 'temperature',
               existing_type=mysql.FLOAT(),
               comment='AI温度参数',
               existing_nullable=True)
    op.alter_column('digital_humans', 'conversation_style',
               existing_type=mysql.VARCHAR(length=50),
               comment='对话风格',
               existing_nullable=True)
    op.alter_column('digital_humans', 'personality',
               existing_type=mysql.JSON(),
               comment='性格特征配置',
               existing_nullable=True)
    op.alter_column('digital_humans', 'skills',
               existing_type=mysql.JSON(),
               comment='专业领域技能列表',
               existing_nullable=True)
    op.alter_column('digital_humans', 'type',
               existing_type=mysql.VARCHAR(length=50),
               comment='数字人类型',
               existing_nullable=False)
    op.alter_column('digital_humans', 'avatar_url',
               existing_type=mysql.VARCHAR(length=500),
               comment='头像URL',
               existing_nullable=True)
    op.alter_column('digital_humans', 'detailed_description',
               existing_type=mysql.TEXT(),
               comment='详细介绍',
               existing_nullable=True)
    op.alter_column('digital_humans', 'short_description',
               existing_type=mysql.VARCHAR(length=200),
               comment='简短描述',
               existing_nullable=True)
    op.alter_column('digital_humans', 'name',
               existing_type=mysql.VARCHAR(length=100),
               comment='数字人名称',
               existing_nullable=False)
    op.add_column('digital_human_training_messages', sa.Column('session_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_digital_human_training_messages_id'), table_name='digital_human_training_messages')
    op.drop_index(op.f('ix_digital_human_training_messages_digital_human_id'), table_name='digital_human_training_messages')
    op.create_index('idx_digital_human', 'digital_human_training_messages', ['digital_human_id'], unique=False)
    # ### end Alembic commands ###
