"""Add TrainingSession table and session_id to training messages

Revision ID: 7465e63e0491
Revises: 11ccaae4fb03
Create Date: 2025-09-11 10:52:42.935255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7465e63e0491'
down_revision: Union[str, None] = '11ccaae4fb03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('digital_human_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(length=100), nullable=False),
    sa.Column('session_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'applied', 'cancelled', name='training_status'), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=True),
    sa.Column('extracted_entities', sa.Integer(), nullable=True),
    sa.Column('extracted_relations', sa.Integer(), nullable=True),
    sa.Column('knowledge_summary', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['digital_human_id'], ['digital_humans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_sessions_digital_human_id'), 'training_sessions', ['digital_human_id'], unique=False)
    op.create_index(op.f('ix_training_sessions_id'), 'training_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_training_sessions_thread_id'), 'training_sessions', ['thread_id'], unique=True)
    op.create_index(op.f('ix_training_sessions_user_id'), 'training_sessions', ['user_id'], unique=False)
    op.alter_column('conversation_checkpoints', 'version',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='检查点版本号',
               existing_nullable=False)
    op.alter_column('conversation_checkpoints', 'parent_version',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='父版本号，用于分支',
               existing_nullable=True)
    op.alter_column('conversation_checkpoints', 'checkpoint_data',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='完整的检查点数据',
               existing_nullable=False)
    op.alter_column('conversation_checkpoints', 'channel_values',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='通道值（消息等）',
               existing_nullable=False)
    op.alter_column('conversation_checkpoints', 'channel_versions',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='通道版本信息',
               existing_nullable=True)
    op.alter_column('conversation_checkpoints', 'metadata',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='检查点元数据',
               existing_nullable=True)
    op.alter_column('conversation_checkpoints', 'task_id',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='任务ID',
               existing_nullable=True)
    op.alter_column('conversations', 'title',
               existing_type=mysql.VARCHAR(length=200),
               comment=None,
               existing_comment='会话标题',
               existing_nullable=True)
    op.alter_column('conversations', 'thread_id',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='LangChain线程ID',
               existing_nullable=False)
    op.alter_column('conversations', 'status',
               existing_type=mysql.ENUM('active', 'archived', 'deleted'),
               comment=None,
               existing_comment='会话状态',
               existing_nullable=True)
    op.alter_column('conversations', 'last_message_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='最后消息时间',
               existing_nullable=True)
    op.add_column('digital_human_training_messages', sa.Column('session_id', sa.Integer(), nullable=True))
    op.alter_column('digital_human_training_messages', 'role',
               existing_type=mysql.ENUM('user', 'assistant'),
               comment=None,
               existing_comment='消息角色',
               existing_nullable=False)
    op.alter_column('digital_human_training_messages', 'content',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='消息内容',
               existing_nullable=False)
    op.alter_column('digital_human_training_messages', 'extracted_knowledge',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='抽取的知识（实体和关系）',
               existing_nullable=True)
    op.alter_column('digital_human_training_messages', 'extraction_metadata',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='知识提取的溯源信息',
               existing_nullable=True)
    op.drop_index('idx_digital_human', table_name='digital_human_training_messages')
    op.create_index(op.f('ix_digital_human_training_messages_digital_human_id'), 'digital_human_training_messages', ['digital_human_id'], unique=False)
    op.create_index(op.f('ix_digital_human_training_messages_id'), 'digital_human_training_messages', ['id'], unique=False)
    op.create_index(op.f('ix_digital_human_training_messages_session_id'), 'digital_human_training_messages', ['session_id'], unique=False)
    op.create_foreign_key(None, 'digital_human_training_messages', 'training_sessions', ['session_id'], ['id'])
    op.alter_column('digital_humans', 'name',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='数字人名称',
               existing_nullable=False)
    op.alter_column('digital_humans', 'short_description',
               existing_type=mysql.VARCHAR(length=200),
               comment=None,
               existing_comment='简短描述',
               existing_nullable=True)
    op.alter_column('digital_humans', 'detailed_description',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='详细介绍',
               existing_nullable=True)
    op.alter_column('digital_humans', 'avatar_url',
               existing_type=mysql.VARCHAR(length=500),
               comment=None,
               existing_comment='头像URL',
               existing_nullable=True)
    op.alter_column('digital_humans', 'type',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='数字人类型',
               existing_nullable=False)
    op.alter_column('digital_humans', 'skills',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='专业领域技能列表',
               existing_nullable=True)
    op.alter_column('digital_humans', 'personality',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='性格特征配置',
               existing_nullable=True)
    op.alter_column('digital_humans', 'conversation_style',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='对话风格',
               existing_nullable=True)
    op.alter_column('digital_humans', 'temperature',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='AI温度参数',
               existing_nullable=True)
    op.alter_column('digital_humans', 'max_tokens',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='最大token数',
               existing_nullable=True)
    op.alter_column('digital_humans', 'system_prompt',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='系统提示词',
               existing_nullable=True)
    op.alter_column('digital_humans', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='模板是否启用（启用后可用于创建对话）',
               existing_nullable=True)
    op.alter_column('digital_humans', 'is_public',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否公开模板',
               existing_nullable=True)
    op.alter_column('messages', 'conversation_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='对话ID',
               existing_nullable=False)
    op.alter_column('messages', 'role',
               existing_type=mysql.ENUM('user', 'assistant', 'system'),
               comment=None,
               existing_comment='消息角色',
               existing_nullable=False)
    op.alter_column('messages', 'content',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='消息内容',
               existing_nullable=False)
    op.alter_column('messages', 'tokens_used',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='使用的token数量',
               existing_nullable=True)
    op.alter_column('messages', 'message_metadata',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='消息元数据',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'message_metadata',
               existing_type=mysql.JSON(),
               comment='消息元数据',
               existing_nullable=True)
    op.alter_column('messages', 'tokens_used',
               existing_type=mysql.INTEGER(),
               comment='使用的token数量',
               existing_nullable=True)
    op.alter_column('messages', 'content',
               existing_type=mysql.TEXT(),
               comment='消息内容',
               existing_nullable=False)
    op.alter_column('messages', 'role',
               existing_type=mysql.ENUM('user', 'assistant', 'system'),
               comment='消息角色',
               existing_nullable=False)
    op.alter_column('messages', 'conversation_id',
               existing_type=mysql.INTEGER(),
               comment='对话ID',
               existing_nullable=False)
    op.alter_column('digital_humans', 'is_public',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否公开模板',
               existing_nullable=True)
    op.alter_column('digital_humans', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment='模板是否启用（启用后可用于创建对话）',
               existing_nullable=True)
    op.alter_column('digital_humans', 'system_prompt',
               existing_type=mysql.TEXT(),
               comment='系统提示词',
               existing_nullable=True)
    op.alter_column('digital_humans', 'max_tokens',
               existing_type=mysql.INTEGER(),
               comment='最大token数',
               existing_nullable=True)
    op.alter_column('digital_humans', 'temperature',
               existing_type=mysql.FLOAT(),
               comment='AI温度参数',
               existing_nullable=True)
    op.alter_column('digital_humans', 'conversation_style',
               existing_type=mysql.VARCHAR(length=50),
               comment='对话风格',
               existing_nullable=True)
    op.alter_column('digital_humans', 'personality',
               existing_type=mysql.JSON(),
               comment='性格特征配置',
               existing_nullable=True)
    op.alter_column('digital_humans', 'skills',
               existing_type=mysql.JSON(),
               comment='专业领域技能列表',
               existing_nullable=True)
    op.alter_column('digital_humans', 'type',
               existing_type=mysql.VARCHAR(length=50),
               comment='数字人类型',
               existing_nullable=False)
    op.alter_column('digital_humans', 'avatar_url',
               existing_type=mysql.VARCHAR(length=500),
               comment='头像URL',
               existing_nullable=True)
    op.alter_column('digital_humans', 'detailed_description',
               existing_type=mysql.TEXT(),
               comment='详细介绍',
               existing_nullable=True)
    op.alter_column('digital_humans', 'short_description',
               existing_type=mysql.VARCHAR(length=200),
               comment='简短描述',
               existing_nullable=True)
    op.alter_column('digital_humans', 'name',
               existing_type=mysql.VARCHAR(length=100),
               comment='数字人名称',
               existing_nullable=False)
    op.drop_constraint(None, 'digital_human_training_messages', type_='foreignkey')
    op.drop_index(op.f('ix_digital_human_training_messages_session_id'), table_name='digital_human_training_messages')
    op.drop_index(op.f('ix_digital_human_training_messages_id'), table_name='digital_human_training_messages')
    op.drop_index(op.f('ix_digital_human_training_messages_digital_human_id'), table_name='digital_human_training_messages')
    op.create_index('idx_digital_human', 'digital_human_training_messages', ['digital_human_id'], unique=False)
    op.alter_column('digital_human_training_messages', 'extraction_metadata',
               existing_type=mysql.JSON(),
               comment='知识提取的溯源信息',
               existing_nullable=True)
    op.alter_column('digital_human_training_messages', 'extracted_knowledge',
               existing_type=mysql.JSON(),
               comment='抽取的知识（实体和关系）',
               existing_nullable=True)
    op.alter_column('digital_human_training_messages', 'content',
               existing_type=mysql.TEXT(),
               comment='消息内容',
               existing_nullable=False)
    op.alter_column('digital_human_training_messages', 'role',
               existing_type=mysql.ENUM('user', 'assistant'),
               comment='消息角色',
               existing_nullable=False)
    op.drop_column('digital_human_training_messages', 'session_id')
    op.alter_column('conversations', 'last_message_at',
               existing_type=mysql.DATETIME(),
               comment='最后消息时间',
               existing_nullable=True)
    op.alter_column('conversations', 'status',
               existing_type=mysql.ENUM('active', 'archived', 'deleted'),
               comment='会话状态',
               existing_nullable=True)
    op.alter_column('conversations', 'thread_id',
               existing_type=mysql.VARCHAR(length=100),
               comment='LangChain线程ID',
               existing_nullable=False)
    op.alter_column('conversations', 'title',
               existing_type=mysql.VARCHAR(length=200),
               comment='会话标题',
               existing_nullable=True)
    op.alter_column('conversation_checkpoints', 'task_id',
               existing_type=mysql.VARCHAR(length=100),
               comment='任务ID',
               existing_nullable=True)
    op.alter_column('conversation_checkpoints', 'metadata',
               existing_type=mysql.JSON(),
               comment='检查点元数据',
               existing_nullable=True)
    op.alter_column('conversation_checkpoints', 'channel_versions',
               existing_type=mysql.JSON(),
               comment='通道版本信息',
               existing_nullable=True)
    op.alter_column('conversation_checkpoints', 'channel_values',
               existing_type=mysql.JSON(),
               comment='通道值（消息等）',
               existing_nullable=False)
    op.alter_column('conversation_checkpoints', 'checkpoint_data',
               existing_type=mysql.JSON(),
               comment='完整的检查点数据',
               existing_nullable=False)
    op.alter_column('conversation_checkpoints', 'parent_version',
               existing_type=mysql.INTEGER(),
               comment='父版本号，用于分支',
               existing_nullable=True)
    op.alter_column('conversation_checkpoints', 'version',
               existing_type=mysql.INTEGER(),
               comment='检查点版本号',
               existing_nullable=False)
    op.drop_index(op.f('ix_training_sessions_user_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_thread_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_digital_human_id'), table_name='training_sessions')
    op.drop_table('training_sessions')
    # ### end Alembic commands ###
